VideoDistributionAdmin/Controllers/ReportController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;
using VideoDistribution.Models;

namespace VideoDistribution.Controllers
{
    [Authorize(Roles = "Superadmin,Admin")]
    public class ReportController : Controller
    {

        public ActionResult Index()
        {
            return View();
        }

        public JsonResult GetReport(string sortdatafield, string sortorder, int pagesize, int pagenum)
        {

            using (VideoDistributionDataContext db = new VideoDistributionDataContext())
            {
                var query = Request.QueryString;
                var dbResult = db.ExecuteQuery<view_ADM_ReportNotification>(Utils.Utils.BuildQuery(query, "view_ADM_ReportNotification")).OrderByDescending(g => g.AddedDate).ToList();
                var videos = from video in dbResult
                             select new view_ADM_ReportNotification
                             {
                                 AddedDate=video.AddedDate,
                                 Name=video.Name,
                                 Title=video.Title,
                                 Url=video.Url,
                                 Id=video.Id,
                                 IsResolved=video.IsResolved
                             };
                var total = dbResult.Count();
                videos = videos.Skip(pagesize * pagenum).Take(pagesize);
                if (sortdatafield != null && sortorder != "")
                {
                    videos =Utils.Utils.SortOrders(videos, sortdatafield, sortorder);
                }
                var result = new
                {
                    TotalRows = total,
                    Rows = videos
                };
                return Json(result, JsonRequestBehavior.AllowGet);

            }
        }

        public JsonResult ResolveReportedVideo(string title)
        {
            StringBuilder result = new StringBuilder();
            
            try
            {
                if (string.IsNullOrEmpty(title))
                {
                    result.AppendLine("Reported video must have a Title.");
                    return Json(new { result = result.ToString() });
                }
                
                using (var db = new VideoDistributionDataContext())
                {
                    db.ADM_ResolveRelatedVideo(title);
                    result.AppendLine("RESOLUTION IS SUCCESSFUL!!!");
                }
            }
            catch (Exception ex)
            {
                result.AppendLine("RESOLUTION HAS ERROR!!!");
                result.AppendLine(ex.Message);
            }
            
            return Json(new { result = result.ToString() });
        }
    }
}

VideoDistributionAdmin/Controllers/VideosController.cs
using VideoDistribution.Models;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Web.Mvc;

namespace VideoDistribution.Controllers
{
    [Authorize(Roles = "SuperAdmin,Admin")]
    public class VideosController : Controller
    {
        public string SortDataField
        {
            get
            {
                var sortDataField = "Id";
                if (Request.QueryString.GetValues("sortdatafield") != null && Request.QueryString.GetValues("sortdatafield").ToList().Count > 0)
                    sortDataField = Request.QueryString.GetValues("sortdatafield")[0];
                return sortDataField;
            }
        }

        public string SortOrder
        {
            get
            {
                var sortOrder = "desc";
                if (Request.QueryString.GetValues("sortorder") != null && Request.QueryString.GetValues("sortorder").ToList().Count > 0)
                    sortOrder = Request.QueryString.GetValues("sortorder")[0].ToUpper();
                return sortOrder;
            }
        }

        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public ActionResult Edit(string id,string type)
        {
            var db = new VideoDistributionDataContext();
            var result = db.ADM_VideoById(id).FirstOrDefault();
            ViewBag.VideoMd5 = id;
            ViewBag.Category = new SelectList(db.GetCategories(), "Id", "Title", result.CategoryId);
            ViewBag.Company = new SelectList(db.STAT_getUsersList("s1").OrderBy(u => u.CompanyName), "Id", "CompanyName", result.UserId);
            ViewBag.Privacy = new SelectList(db.GetVideoPrivacy(), "Id", "Title", result.PrivacyId);
            var visibility = new List<int>() { 0, 1 };
            ViewBag.Visible = new SelectList(visibility, result.Visible);
            ViewBag.type = type;
            ViewBag.Title = result.Title;
            //ViewBag.GameTypes = new SelectList(db.GetGameTypes(), "Id", "TypeName", result.GameType);
            return View(result);
        }

        public JsonResult UpdateVideosInline(view_ADM_Video result)
        {
            using (var db = new VideoDistributionDataContext())
            {
                db.UpdateVideo(null,result.VideoMd5,result.Title,Convert.ToBoolean(result.Approved),Convert.ToBoolean(result.Visible),Convert.ToBoolean(result.Banner),
                    null,null,null,null,null,null,null,null,null
                );
                return Json(true, JsonRequestBehavior.AllowGet);
            }
        }

        [HttpPost]
        public ActionResult Edit(ADM_VideoByIdResult result)
        {
            var db = new VideoDistributionDataContext();
            db.UpdateVideo(
                result.UserId, 
                result.VideoMd5, 
                result.Title, 
                null, 
                Convert.ToBoolean(result.Visible), 
                Convert.ToBoolean(null), 
                result.Warning, 
                result.VideoType, 
                result.Width, 
                result.Height, 
                result.ExternalURL, 
                result.Description, 
                result.Filename, 
                Convert.ToInt32(result.Category),
                Convert.ToInt32(result.Privacy)
            );
            return RedirectToAction("Index");
        }

        public JsonResult GetVideos(string sortdatafield, string sortorder, int pagesize, int pagenum)
        {
            using (VideoDistributionDataContext db = new VideoDistributionDataContext())
            {
                var query = Request.QueryString;
                var dbResult = db.ExecuteQuery<view_ADM_Video>(Utils.Utils.BuildQuery(query, "view_ADM_Videos")).ToList();
                var videos = from video in dbResult
                            select new view_ADM_Video
                            {
                                Id = video.Id,
                                VideoMd5 = video.VideoMd5,
                                Title = video.Title,
                                Warning = video.Warning,
                                Approved = video.Approved,
                                Visible = video.Visible,
                                Banner = video.Banner,
                                AddedDate = video.AddedDate,
                                CompanyName  = video.CompanyName,
                                UserId = video.UserId,
                                VideoType = video.VideoType,
                                ProviderId = video.ProviderId,
                                ProviderName = video.ProviderName
                            };


                var total = dbResult.Count();
                if (this.SortDataField != null && this.SortOrder != "")
                {
                    videos = Utils.Utils.SortOrders<view_ADM_Video>(videos, this.SortDataField, this.SortOrder);
                }
                videos = videos.Skip(pagesize * pagenum).Take(pagesize);
                var result = new
                {
                    TotalRows = total,
                    Rows = videos
                };
               return Json(result, JsonRequestBehavior.AllowGet);
            }
        }

        public ActionResult Feature(int id)
        {
            var db = new VideoDistributionDataContext();
            var result = db.APP_InsertFeaturedVideos(id.ToString());
            return RedirectToAction("Index", "FeaturedVideos");
        }

        public ActionResult Report()
        {
            return View();
        }

        [Authorize(Roles = "Superadmin")]
        public JsonResult GetVideosByCategoryAndAccount()
        {
            using (VideoDistributionDataContext db = new VideoDistributionDataContext())
            {
                var result = db.ADM_VideosByCategoryAndAccount().ToList();
                var categoryResult = result.GroupBy(r => r.CatTitle)
                                           .Select(group => new { Category = group.Key, Count = group.Sum(x => x.VideoCount)})
                                           .OrderBy(y => y.Category);
                var accountResult = result.GroupBy(r => r.AccountName)
                                           .Select(group => new { Account = group.Key, Count = group.Sum(x => x.VideoCount) })
                                           .OrderBy(y => y.Account);
                var finalresult = new
                {
                    Category = categoryResult,
                    Account = accountResult
                };
                return Json(finalresult, JsonRequestBehavior.AllowGet);
            }
        }
    }
}

VideoDistributionAdmin/Views/Videos/Edit.cshtml
@using VideoDistribution.Enums;
@model VideoDistribution.Models.ADM_VideoByIdResult

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
  
}

<script src="~/Scripts/jquery-1.10.2.min.js"></script>

<div class="column" style="min-width:35% !important; ">
    @using (Html.BeginForm("Edit", "Videos"))
    {
        <div asp-validation-summary="All"></div>
        <div>
            @Html.Label("Partner")
            @Html.DropDownList("Company")
        </div>
        <div style="margin-top:15px;">
            @Html.Label("Title")
            @Html.TextBoxFor(model => model.Title)
            @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
        </div>
        <div  style="margin-top:15px;">
            @Html.Label("Category")
            @Html.DropDownList("Category")
        </div>
        
        <div style="margin-top:15px;">
            @Html.Label("Visible")
            @Html.DropDownList("Visible")
        </div>
        
        <div style="margin-top:15px;">
            @Html.LabelFor(model => model.Description)
            @Html.TextAreaFor(model => model.Description)
            @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
        </div>
        <div style="margin-top:15px;">
            @Html.Label("External URL")
            @Html.TextBoxFor(model => model.ExternalURL, new { disabled = "disabled" })
            @Html.ValidationMessageFor(model => model.ExternalURL, "", new { @class = "text-danger" })
        </div>
        <div style="margin-top:15px;">
            @Html.LabelFor(model => model.ExternalThumbURL)
            @Html.TextBoxFor(model => model.ExternalThumbURL, new { disabled = "disabled" })
            @Html.ValidationMessageFor(model => model.ExternalThumbURL, "", new { @class = "text-danger" })
        </div>
        <div style="margin-top:15px;">
            @Html.Label("Video Md5")
            @Html.TextBoxFor(model => model.VideoMd5, new { disabled = "disabled" })
            @Html.ValidationMessageFor(model => model.VideoMd5, "", new { @class = "text-danger" })
        </div>
        <div style="margin-top:15px;">
            @Html.Label("File Name")
            @Html.TextBoxFor(model => model.Filename, new { disabled = "disabled" })
            @Html.ValidationMessageFor(model => model.Filename, "", new { @class = "text-danger" })
        </div>
        <div>
            @Html.Label("Privacy")
            @Html.DropDownList("Privacy")
        </div>
        <div style="margin-top:15px;">
            @Html.Label("Added On")
            @Html.TextBoxFor(model => model.AddedDate, new { disabled = "disabled" })
            @*@Html.EditorFor(model => model.AddedOn, new { @Value = Model.AddedOn.ToString() , htmlAttributes = new { @class = "form-control", @disabled = "disabled" } })*@
            @Html.ValidationMessageFor(model => model.AddedDate, "", new { @class = "text-danger" })
        </div>

        @Html.HiddenFor(model => model.Id)
        @Html.HiddenFor(model => model.VideoMd5)
        @Html.HiddenFor(model => model.UserId)
        <div style="margin-top:15px;">
            <button type="submit" class="button active" style="text-align:center">Save</button>
        </div>
    }
</div>
<div class="column" style = "margin-left:30px;">
    <div align="left" id="divVideo">
        @{ double proportion = (double)(600 / ((double)((double)Model.Width / (double)Model.Height)));}
        <form style="width:600px !important;">
            <label>@Model.Title</label>
        </form>
        <iframe id="videoEmbedded"
                src="@String.Concat("http://player.videodistribution.com/index.html?videoid=" + Model.VideoMd5)"
                style="width:100%;height:500px"
                scrolling="auto" frameborder="0"></iframe>    
    </div>
    <form style="width:600px !important;">
        <label>Thumbnail</label>
        <div class="screenshots" align="left">
            <img src="@Model.ExternalThumbURL" width="222" height="140" />
        </div>
    </form>
    <div class="row">
      
        <br />
      

        @if(ViewBag.type == "rejected")
        {

            <button class="button active" style="text-align:center" id="btnUnRejected">Unreject</button>
        }
        else if(ViewBag.type == "waiting")
        {
            <div>
                Reason: <textarea id="rejectedReason" rows="4" style="width:350px"></textarea>
            </div>
            <button class="button active" style="text-align:center" id="btnApprove">Approve</button>
            <button class="button active" style="text-align:center" id="btnRejected">Reject</button>
            <button class="button active" style="text-align:center" id="btnDelete">Delete</button>

        }
        else if (ViewBag.type == "published")
        {
            <div>
                Reason: <textarea id="rejectedReason" rows="4" style="width:350px"></textarea>
            </div>
            <button class="button active" style="text-align:center" id="btnRejected">Reject</button>
            <button class="button active" style="text-align:center" id="btnDelete">Delete</button>

        }
        else if (ViewBag.type == "private")
        {
            <div>
                 Reason: <textarea  id="rejectedReason" rows="4" style="width:350px"></textarea>
            </div>
            <button class="button active" style="text-align:center" id="btnRejected">Reject</button>
            <button class="button active" style="text-align:center" id="btnWatched">Watched</button>

        }
        else if (ViewBag.type == "deleted")
        {

            <button class="button active" style="text-align:center" id="btnActivated">Activate</button>

        }

    </div>
</div>

@section scripts{
    <script>
        $(document).ready(function () {
            $("#btnApprove").click(function () {
                window.location.href = '@String.Concat("/VideoApprove/Approve?videoMd5=" + @ViewBag.VideoMd5)';
            });

            $("#btnUnRejected").click(function () {
                window.location.href = '@String.Concat("/VideoApprove/UnApprove?videoMd5=" + @ViewBag.VideoMd5)';

            });

            $("#btnActivated").click(function () {
                window.location.href = '@String.Concat("/VideoApprove/ActiveteVideo?videoMd5=" + @ViewBag.VideoMd5)';

            });


            $("#btnWatched").click(function () {
                var urls = "/VideoApprove/ChangeStatus?videoMd5=" +'@ViewBag.VideoMd5' +"&type=" + '@VideoDistAdminEnums.VideoStatusEnum.Watched.ToString()';
                window.location.href = urls;

            });


            $("#btnDelete").click(function () {

                //window.location.href = '/VideoApprove/DeleteVideo?videoMd5=' + '@ViewBag.VideoMd5';

                if ($("#rejectedReason").val() == "") {
                    alert("Please write reason");
                    return;

                }
                else {
                    window.location.href = '/VideoApprove/DeleteVideo?videoMd5=' + '@ViewBag.VideoMd5' + "&reason=" + $("#rejectedReason").val()
                                                                      + '&title=' + '@ViewBag.Title';
                }


            });

            $("#btnRejected").click(function () {

                if( $("#rejectedReason").val() =="")
                {
                    alert("Please write reason");
                    return;

                }
                else
                {
                    window.location.href = '/VideoApprove/Rejected?videoMd5=' + '@ViewBag.VideoMd5' + "&reason=" + $("#rejectedReason").val()
                                                                   + '&title=' + '@ViewBag.Title';
                }


            });

        });
    </script>

}

VideoDistributionAdmin/Views/Videos/Report.cshtml

@{
    ViewBag.Title = "Report";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="column" ng-controller="videoReportCtrl">
    <div class="row" style="padding: 15px;">
        <div style="width: 50%;" class="col-md-5">
            <h4 style="text-transform: uppercase;">Videos By Category</h4>
            <div>
                <canvas id="myChart"></canvas>
            </div>
        </div>
        <div style="width: 50%;" class="col-md-5">
            <h4 style="text-transform: uppercase;">Videos By Account</h4>
            <div>
                <canvas id="myChart2"></canvas>
            </div>
        </div>
    </div>
</div>






@section scripts{
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">

    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script>
        function getRandomInt(min, max) {
            return Math.floor(Math.random() * (max - min + 1)) + min;
        }

        function randomColor(brightness) {
            function randomChannel(brightness) {
                var r = 255 - brightness;
                var n = 0 | ((Math.random() * r) + brightness);
                var s = n.toString(16);
                return (s.length == 1) ? '0' + s : s;
            }
            return '#' + randomChannel(brightness) + randomChannel(brightness) + randomChannel(brightness);
        };

        $.post("/Videos/GetVideosByCategoryAndAccount", null, function (data) {
            debugger;
            var ctx = document.getElementById('myChart').getContext('2d');
            var labels = [];
            var accountData = [];
            var colors = [];

            $.each(data.Account, function (index, value) {
                labels.push(value.Account);
                accountData.push(value.Count);
                colors.push(randomColor(getRandomInt(0, 255)));
            });

            var myChart = new Chart(ctx, {
                type: 'pie',
                data: {
                    labels: labels,
                    datasets: [{
                        backgroundColor: colors,
                        data: accountData
                    }]
                }
            });

            var ctx2 = document.getElementById('myChart2').getContext('2d');
            var dataSet = [];
            labels = [];
            var categoryData = [];
            colors = [];

            $.each(data.Category, function (index, value) {
                labels.push(value.Category);
                categoryData.push(value.Count);
            });

            dataSet.push({ label: 'Count', data: categoryData, backgroundColor: "rgba(214,207,33,0.8)" });

            var myChart = new Chart(ctx2, {
                type: 'bar',
                data: {
                    labels: labels,
                    datasets: dataSet
                }
            });
        });

    </script>
}



